# Pin1 docked poses — generated by the Dance with Inhibition GUI.
# Sub-pocket definitions come from integration/app/pose3d.py:SUBPOCKETS,
# so this session and the GUI cannot disagree about where they are.

load 6VAJ_prepared.pdb, receptor
load d_c04a00026998_docked.sdf, poses

hide everything
show surface, receptor
set transparency, 0.25
color grey80, receptor
show sticks, poses
color cyan, poses and elem C
set all_states, on          # every docked mode at once

# proline-binding pocket: The hydrophobic slot that accepts the prolyl ring of a pSer/pThr-Pro substrate. Leu122/Met130/Phe134 are the canonical lining (Ranganathan 1997; Behrsin 2007); Gln131 caps the rim and hydrogen-bonds sulfopin's sulfone at 2.9 A here. The sulfopin paper's wider description adds Thr152/His157, which this view colours with the catalytic site instead.
select proline, receptor and resi 122+130+131+134
color orange, proline
label proline and name CA and resi 122, "proline-binding pocket"

# phosphate-binding Arg loop: The basic triad on the catalytic loop (residues 63-80) that grips the substrate phosphate — the reason Pin1 is phospho-specific, and the reason an anionic group on a ligand has somewhere to go. Ser71 sits in the same loop but is a phosphosite, not part of the triad, so it is not coloured here.
select phosphate, receptor and resi 63+68+69
color royalblue, phosphate
label phosphate and name CA and resi 63, "phosphate-binding Arg loop"

# Cys113 pocket (catalytic tetrad): The catalytic tetrad Cys113/His59/His157/Ser154. This is where T_3 and T_4 form their covalent bond and where sulfopin's chloroacetamide alkylates the SG (1.78 A in 6VAJ). NOTE: Cys113 is alkylated by covalent INHIBITORS, but in native catalysis the current reading is that it stabilises the cis conformer electrostatically rather than attacking as a nucleophile (Vohringer-Martinez 2014) — so 'catalytic cysteine' names the residue, not a covalent step in the enzyme's own mechanism.
select cys113, receptor and resi 59+113+154+157
color yellow, cys113
label cys113 and name CA and resi 59, "Cys113 pocket (catalytic tetrad)"

select cys113_sg, receptor and resi 113 and name SG
show spheres, cys113_sg
color yellow, cys113_sg

# The covalent link gnina was told to form (--covalent_rec_atom A:113:SG).
# Measured, not drawn as a bond: the adduct and the receptor are separate objects here.
distance covalent_link, cys113_sg, poses within 2.4 of cys113_sg
color yellow, covalent_link

orient poses
zoom poses, 6
deselect
