"""
Purpose: cover the XVG parser and the class-membership test — two catalogued defect shapes.
Author: Mike Hallett (with Claude Code)
Date: 2026-08-05
Input: shared/gromacs_analysis.py, shared/decoys_classmatched.py
Output: pass/fail

Second pass over the decision-affected modules no test referenced. These two
were picked because each sits on a shape `docs/how_this_project_breaks.md`
already names as a live lead:

* **"Every parser that assumes one input shape."** `_read_xvg` reads GROMACS
  output, and catalogue entry #20 is a parser that handled one of mmCIF's two
  serialisations and reported **zero covalent entries across all 190**, which
  reads as a finding rather than a parse failure. The XVG reader feeds the
  ligand-RMSD numbers behind D0038 and D0044.

* **The class pattern has already failed twice.** `warhead_group_pattern`'s own
  docstring records building the pattern with `MolFromSmiles` instead of
  `MolFromSmarts`, so `[*]` meant "a dummy atom" rather than "any atom" and
  matched **0 of 2,038** chloroacetamides while the pools held thousands. D0042
  is the second: the SNAr class had three decoys because its pattern described
  one molecule. Both produced populated, plausible, wrong output.

WHAT IS DELIBERATELY NOT TESTED. The subprocess drivers around them -- `gmx`
invocations, HTTP pool fetches -- need the tools and the network, and mocking
them would assert that the mock works.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from shared import gromacs_analysis as ga          # noqa: E402


# --- the XVG parser -------------------------------------------------------

def _xvg(body: str, tmp_path: Path) -> Path:
    p = tmp_path / "rmsd.xvg"
    p.write_text(body)
    return p


def test_reads_a_normal_two_column_xvg(tmp_path):
    f = _xvg("# comment\n@ title \"RMSD\"\n0.0 0.150\n10.0 0.230\n20.0 0.198\n",
             tmp_path)
    a = ga._read_xvg(f)
    assert a.shape == (3, 2)
    assert a[0, 0] == 0.0 and a[1, 1] == pytest.approx(0.230)


def test_both_gromacs_comment_markers_are_stripped(tmp_path):
    """GROMACS writes `#` comments AND `@` metadata. Treating only one as a
    comment makes the other parse as data or abort the read."""
    f = _xvg("@    xaxis label \"Time (ps)\"\n"
             "@ s0 legend \"RMSD\"\n"
             "# generated by gmx rms\n"
             "0.0 0.1\n1.0 0.2\n", tmp_path)
    assert ga._read_xvg(f).shape == (2, 2)


def test_extra_columns_do_not_break_the_read(tmp_path):
    """`gmx` emits more than two columns for some analyses; the reader takes
    the first two rather than refusing the file."""
    f = _xvg("0.0 0.15 0.9 1.2\n1.0 0.23 0.8 1.1\n", tmp_path)
    a = ga._read_xvg(f)
    assert a.shape == (2, 2)
    assert a[1, 1] == pytest.approx(0.23)


def test_a_file_with_no_data_rows_raises_rather_than_returning_empty(tmp_path):
    """THE ENTRY-#20 CASE. A header-only XVG must not read as 'zero RMSD' or
    as an empty trajectory -- both are plausible-looking results. It has to be
    an error, because it means the analysis did not run."""
    f = _xvg("# gmx rms\n@ title \"RMSD\"\n", tmp_path)
    with pytest.raises(ga.AnalysisError):
        ga._read_xvg(f)


def test_a_missing_file_raises_rather_than_returning_empty(tmp_path):
    with pytest.raises(ga.AnalysisError):
        ga._read_xvg(tmp_path / "never_written.xvg")


def test_unparseable_rows_are_skipped_not_fatal(tmp_path):
    """A truncated final line is normal when a run is killed mid-write. The
    good rows must survive it."""
    f = _xvg("0.0 0.15\n1.0 0.23\n2.0 nan_garbage\n3.0 0.31\n", tmp_path)
    a = ga._read_xvg(f)
    assert a.shape == (3, 2)
    assert a[-1, 1] == pytest.approx(0.31)


def test_a_wholly_unparseable_file_raises(tmp_path):
    """Skipping bad rows must not degrade into silently returning nothing."""
    f = _xvg("not data\nalso not data\n", tmp_path)
    with pytest.raises(ga.AnalysisError):
        ga._read_xvg(f)


# --- the class-membership pattern ----------------------------------------

@pytest.fixture(scope="module")
def dcm():
    """Imported lazily: it pulls RDKit and the warhead library."""
    from shared import decoys_classmatched as m
    return m


def test_the_group_pattern_is_built_from_SMARTS_not_SMILES(dcm):
    """The documented failure, pinned.

    In SMARTS `[*]` is "any atom"; in SMILES it is a dummy of atomic number 0
    that matches only another dummy. Built the wrong way, the pattern matched
    0 of 2,038 chloroacetamides and every chemotype was reported chemically
    unavailable while the pools held thousands of molecules.
    """
    from rdkit import Chem

    row = {"group_smarts": "[*]C(=O)C[Cl]"}
    pat = dcm.warhead_group_pattern(row)
    assert pat is not None

    # A real chloroacetamide must match the pattern the code actually builds.
    mol = Chem.MolFromSmiles("CN(C)C(=O)CCl")
    assert mol.HasSubstructMatch(pat), (
        "the group pattern does not match a chloroacetamide — this is the "
        "SMILES-vs-SMARTS failure the docstring records")

    # And the wrong construction must NOT match, so the test can tell them apart.
    wrong = Chem.MolFromSmiles("[*]C(=O)C[Cl]")
    assert wrong is None or not mol.HasSubstructMatch(wrong), (
        "SMILES-built pattern matched; this test cannot distinguish the "
        "correct construction from the broken one")


def test_a_malformed_smarts_yields_None_rather_than_a_pattern_that_matches_nothing(dcm):
    """None is checkable; a pattern that silently matches nothing is not.

    `verify_class` treats None as 'not a member', so a typo'd SMARTS empties a
    class rather than producing a class whose members are all rejected for a
    reason nobody can see.
    """
    assert dcm.warhead_group_pattern({"group_smarts": "C(=O"}) is None


def test_verify_class_refuses_a_molecule_without_the_group(dcm):
    """Membership needs the reactive group, not merely a parseable molecule."""
    from rdkit import Chem
    pat = Chem.MolFromSmarts("[*]C(=O)C[Cl]")
    assert dcm.verify_class("c1ccccc1", "chloroacetamide", pat, None) is False


def test_verify_class_refuses_an_unparseable_smiles(dcm):
    from rdkit import Chem
    pat = Chem.MolFromSmarts("[*]C(=O)C[Cl]")
    assert dcm.verify_class("not_a_smiles(((", "chloroacetamide", pat, None) is False


def test_verify_class_refuses_when_the_pattern_is_None(dcm):
    """A class whose SMARTS failed to compile must admit nobody.

    The alternative -- treating a None pattern as 'no constraint' -- would let
    every retrieved molecule into the class, which is the denylist reading of
    an allowlist and exactly how D0042's SNAr class went wrong in the other
    direction.
    """
    assert dcm.verify_class("CN(C)C(=O)CCl", "chloroacetamide", None, None) is False
