"""
Purpose: T_3 step 1 — LibInvent decoration of the sulfopin scaffold.
Author: Mike Hallett (with Claude Code)
Date: 2026-07-27
Input: config/approaches/t3_reinvent.yaml, the staged libinvent prior
Output: the D3 frame — decorated candidates with the scaffold verified intact

WHAT T_3 IS, AND HOW IT DIFFERS FROM T_4. Both start from sulfopin. T_4
enumerates nine warhead classes against a fixed R-group library and lets the
gates discriminate; T_3 fixes the warhead to acrylamide by expert choice and
spends its entire budget on generative decoration of the other attachment point.
Same seed, opposite allocation of effort — which is why they are separate
approaches rather than one with a flag.

VERIFY THE SCAFFOLD ON EVERY ROW. A generative model asked to decorate a
scaffold will occasionally return something that does not contain it. That is
not a rare pathology to sample for; it is checked on every candidate, because a
molecule missing the covalent warhead is not a T_3 candidate at all and would
sail through docking as a non-covalent binder. The check is the same
`has_substructure` T_4 uses for its core.

THE WARHEAD IS NOT SELECTED HERE. It is fixed in config by PI decision, and
D0019 recorded that acrylamide sits outside the reactivity window anchored on
the verified Pin1 chemotypes. T_3 therefore carries that caveat rather than
resolving it, and the GUI must display it beside T_3's candidates.

REINVENT IS DRIVEN BY A GENERATED TOML, NOT BY HAND. The TOML this writes is
kept next to the output so the run is reproducible from the artifact rather than
from whoever typed the command.
"""

from __future__ import annotations

import argparse
import logging
import subprocess
import sys
from pathlib import Path

import pandas as pd
import yaml

REPO = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(REPO))

from shared import io as dio                      # noqa: E402
from shared import pocket_size as ps              # noqa: E402
from shared import smiles as smi                  # noqa: E402

log = logging.getLogger("t3-generate")

EXPERIMENT = "03_t3_reinvent"
APPROACH = "t3"
CONFIG = REPO / "config" / "approaches" / "t3_reinvent.yaml"
REINVENT_ENV = Path("/data/lab_vm/envs/dwi_reinvent4")
WORK_ROOT = Path("/data/lab_vm/append_only/inhibition") / EXPERIMENT / "generation"
NICE = 19

# The scaffold minus its attachment point — what every product must still
# contain. Written as SMARTS so it matches regardless of how the model wrote it.
SCAFFOLD_SMARTS = "N(C(=O)C=C)C1CCS(=O)(=O)C1"
WARHEAD_SMARTS = "[CX3]=[CX3][CX3]=O"          # the acrylamide Michael acceptor


def load_config() -> dict:
    cfg = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    g = cfg["generation"]
    return {
        "prior": g["prior"],
        "scaffold": g["scaffold_smiles"],
        "n_smiles": int(g["n_smiles"]),
        "unique": bool(g.get("unique_molecules", True)),
        "randomize": bool(g.get("randomize_smiles", True)),
        "device": g.get("device", "cuda:0"),
        "batch_size": int(g.get("batch_size", 128)),
        "mechanism": cfg["approach"]["mechanism"],
        "warhead_class": cfg["warhead"]["class_id"],
        "outside_window": bool(cfg["warhead"].get("outside_reactivity_window", False)),
    }


def write_reinvent_toml(workdir: Path, cfg: dict) -> tuple[Path, Path]:
    """Write the scaffold file and the sampling TOML REINVENT will consume."""
    scaffold_file = workdir / "scaffold.smi"
    scaffold_file.write_text(cfg["scaffold"] + "\n", encoding="utf-8")

    out_csv = workdir / "sampling.csv"
    toml = f"""# Generated by {Path(__file__).name} — do not hand-edit.
run_type = "sampling"
device = "{cfg['device']}"
json_out_config = "{workdir / '_sampling.json'}"

[parameters]
model_file = "{cfg['prior']}"
smiles_file = "{scaffold_file}"
output_file = "{out_csv}"
num_smiles = {cfg['n_smiles']}
unique_molecules = {str(cfg['unique']).lower()}
randomize_smiles = {str(cfg['randomize']).lower()}
"""
    toml_path = workdir / "sampling.toml"
    toml_path.write_text(toml, encoding="utf-8")
    return toml_path, out_csv


def run_reinvent(toml_path: Path, workdir: Path, timeout_s: int = 14400) -> None:
    exe = REINVENT_ENV / "bin" / "reinvent"
    if not exe.is_file():
        raise SystemExit(f"reinvent not found at {exe}; build the dwi_reinvent4 env")
    log.info("running REINVENT sampling (this is the slow part)")
    proc = subprocess.run([str(exe), str(toml_path)], cwd=workdir,
                          capture_output=True, text=True, timeout=timeout_s)
    (workdir / "reinvent.log").write_text(proc.stdout + "\n" + proc.stderr,
                                          encoding="utf-8")
    if proc.returncode != 0:
        raise SystemExit(
            f"reinvent failed ({proc.returncode}); see {workdir/'reinvent.log'}\n"
            + proc.stderr[-800:])


def verify(df: pd.DataFrame) -> pd.DataFrame:
    """Every candidate must still carry the scaffold AND an intact warhead."""
    out = df.copy()
    out["scaffold_intact"] = [smi.has_substructure(s, SCAFFOLD_SMARTS)
                              for s in out["canonical_smiles"]]
    out["warhead_intact"] = [smi.has_substructure(s, WARHEAD_SMARTS)
                             for s in out["canonical_smiles"]]
    bad = ~(out["scaffold_intact"] & out["warhead_intact"])
    out.loc[bad, "rejected_at"] = "scaffold_or_warhead_lost"
    if bad.any():
        log.warning("%d/%d generated molecules lost the scaffold or the warhead "
                    "and are stamped (not deleted)", int(bad.sum()), len(out))

    # POCKET CEILING (issue #1, note 3). T_3's oversized R-groups are NOT the
    # product of multiple decoration cycles: LibInvent runs ONCE here
    # (n_smiles: 20000, one attachment point), so there are no cycles to limit.
    # The prior produces large decorations in a single pass. The lever that
    # actually exists is a size ceiling.
    #
    # Stamped, never deleted. `rejected_at` is how every other stage records a
    # rejection, and keeping the row means the size distribution of what was
    # removed stays visible in the frame rather than only in a log line.
    from rdkit import Chem  # local: keeps module import cost off the CLI path
    out["heavy_atoms"] = [
        (m.GetNumHeavyAtoms() if (m := Chem.MolFromSmiles(str(s))) else None)
        for s in out["canonical_smiles"]]
    already = out["rejected_at"].notna() if "rejected_at" in out.columns \
        else pd.Series(False, index=out.index)
    newly = out["heavy_atoms"].gt(ps.MAX_HEAVY_ATOMS).fillna(False) & ~already
    out.loc[newly, "rejected_at"] = "exceeds_pocket_ceiling"
    if newly.any():
        log.warning("%d/%d generated molecules exceed the %d heavy-atom pocket "
                    "ceiling and are stamped (not deleted); median generated "
                    "size %s heavy atoms", int(newly.sum()), len(out),
                    ps.MAX_HEAVY_ATOMS, out["heavy_atoms"].median())
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="T_3: LibInvent decoration of sulfopin.")
    ap.add_argument("--n", type=int, default=None, help="override num_smiles")
    ap.add_argument("--reuse", action="store_true",
                    help="parse an existing sampling.csv instead of re-running")
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    WORK_ROOT.mkdir(parents=True, exist_ok=True)

    cfg = load_config()
    if args.n:
        cfg["n_smiles"] = args.n
    if not Path(cfg["prior"]).is_file():
        raise SystemExit(f"libinvent prior not staged: {cfg['prior']}\n"
                         "  python -m shared.sources stage --only reinvent_priors")

    toml_path, out_csv = write_reinvent_toml(WORK_ROOT, cfg)
    if not (args.reuse and out_csv.is_file()):
        run_reinvent(toml_path, WORK_ROOT)
    if not out_csv.is_file():
        raise SystemExit(f"reinvent produced no output at {out_csv}")

    raw = pd.read_csv(out_csv)
    log.info("reinvent returned %d rows with columns %s", len(raw), list(raw.columns))
    smiles_col = next((c for c in ("SMILES", "smiles", "Molecule")
                       if c in raw.columns), None)
    if smiles_col is None:
        raise SystemExit(f"no SMILES column in {out_csv} (got {list(raw.columns)})")

    rows = []
    seen: set[str] = set()
    for _, r in raw.iterrows():
        canon = smi.canonical(str(r[smiles_col]))
        if canon is None:
            continue
        key = smi.inchikey(canon)
        if not key or key in seen:
            continue
        seen.add(key)
        rows.append({"canonical_smiles": canon,
                     "candidate_id": smi.candidate_id(canon, prefix=APPROACH),
                     "approach": APPROACH,
                     "nll": float(r["NLL"]) if "NLL" in raw.columns else None,
                     "scaffold_smiles": cfg["scaffold"],
                     "warhead_class": cfg["warhead_class"],
                     "mechanism": cfg["mechanism"],
                     "rejected_at": pd.NA})
    df = pd.DataFrame(rows)
    if df.empty:
        raise SystemExit("no parseable, unique molecules came back from REINVENT")
    df = verify(df)

    out = dio.write_full_frame(
        df, approach=APPROACH, experiment=EXPERIMENT, stage="t3_generate",
        params={"engine": "reinvent4 libinvent",
                "prior": cfg["prior"],
                "scaffold_smiles": cfg["scaffold"],
                "num_smiles_requested": cfg["n_smiles"],
                "warhead_class": cfg["warhead_class"],
                "warhead_fixed_by": "PI decision 2026-07-27",
                "outside_reactivity_window": cfg["outside_window"]},
        inputs={"prior": Path(cfg["prior"])})

    n_ok = int(df["rejected_at"].isna().sum())
    print(f"\nT_3 generation -> {out}")
    print(f"  {len(df)} unique molecules, {n_ok} with scaffold AND warhead intact")
    print(f"  warhead {cfg['warhead_class']} fixed by PI decision"
          + ("; OUTSIDE the reactivity window (D0019)" if cfg["outside_window"] else ""))
    if "nll" in df and df["nll"].notna().any():
        print(f"  NLL median {df['nll'].median():.2f} "
              f"(lower = more likely under the prior)")


if __name__ == "__main__":
    main()
