"""
Purpose: resolve receptor structures BY VERIFIED IDENTITY, so "3IKD" can never mean two different files.
Author: Mike Hallett (with Claude Code)
Date: 2026-08-06
Input: the receptor files on disk
Output: verified paths, or a loud failure

THE PROBLEM THIS EXISTS FOR. There are two structures on this box that both
answer to "3IKD", and they are not the same protein state:

    3IKD_ian        1,807 atoms,   7 waters   chemist-prepared, uploaded by
                    sha256 37cccd49...        @tt8804 2026-08-05. 888 hydrogens
                                              already assigned; the chemist's
                                              protonation is authoritative.

    3IKD_deposited  2,741 atoms, 484 waters   downloaded from RCSB 2026-08-04 by
                    sha256 071ebbdf...        prepare_ensemble_receptors.py, then
                                              put through 6VAJ's prep path
                                              (strip -> reduce -BUILD -> obabel).

Every 2.0.0 result -- the geometric ranking, the elevation experiment, the 100 ns
MD, the covalent workup -- used **3IKD_ian**. But `noncovalent_dock_run` resolves
the ensemble receptors, and its 3IKD is the **deposited** one. So a non-covalent
path and a covalent path in the same repo can both say "3IKD" and mean different
structures, with different waters and different protonation.

WHY A SHA, NOT A CONSTANT. Renaming a path stops the two being confused by a
reader. It does not stop the file underneath being replaced, re-uploaded, or
re-prepared, after which the name is still right and the structure is different.
This module pins the digest and refuses on mismatch, which is the difference
between naming a thing and verifying it. That distinction is the single defect
class 2.0.0 kept rediscovering (D0059, D0067, the PDBQT atom-name keying, the
6VAJ pose rendering): a value taken by name, position or inheritance instead of
by identity.

@tt8804, 2026-08-06: "I also want to make extra sure we are using the prepared
3IKD uploaded by me and not just an accessed 3ikd. From now on refer to the pdb
as 3IKD_ian."
"""

from __future__ import annotations

import hashlib
from pathlib import Path

DATA = Path("/data/lab_vm")

#: The chemist's structure. THE canonical receptor for this project (D0059).
IAN_3IKD_SRC = DATA / "immutable/inhibition/receptor/3ikd_well_prepared.pdb"
IAN_3IKD_SHA = "37cccd49b585c4bce1d1f8e6e8a68aa0178aae2f79f480271cac24e3ccacb68d"

#: Ligand-stripped derivative of the above, which is what the MD/BPMD/covalent
#: paths actually consume. Derived by scripts/prepare_3ikd_receptor.py.
IAN_3IKD_NOLIGAND = DATA / "modifiable/inhibition/receptor_3ikd_prep/3IKD_noligand.pdb"

#: The deposited structure. NOT interchangeable with the above. Named here so it
#: is referred to explicitly rather than as a bare "3IKD".
DEPOSITED_3IKD = DATA / "modifiable/inhibition/ensemble_receptor_prep/3IKD.pdb"
DEPOSITED_3IKD_SHA = "071ebbdf8378bcab"  # prefix only; this file is not pinned

#: Superseded by D0059. Present so that code naming it is obviously naming it.
SUPERSEDED_6VAJ = DATA / "modifiable/inhibition/receptor_prep/6VAJ_prepared.pdb"


class ReceptorIdentityError(RuntimeError):
    """The file at the expected path is not the structure that was pinned."""


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def resolve_3ikd_ian(*, noligand: bool = False, verify: bool = True) -> Path:
    """Return the chemist's 3IKD, having checked it IS the chemist's 3IKD.

    `noligand=True` returns the ligand-stripped derivative used by the MD and
    covalent paths. The digest is pinned on the SOURCE rather than the
    derivative, because the derivative is regenerated by the prep script and its
    digest legitimately changes when the prep changes; the source must not.

    Raises ReceptorIdentityError rather than warning. A receptor that is not the
    one you think it is invalidates every number computed from it, so this is not
    a condition to continue past.
    """
    if not IAN_3IKD_SRC.exists():
        raise ReceptorIdentityError(
            f"3IKD_ian source is missing: {IAN_3IKD_SRC}. This is the "
            f"chemist-prepared structure uploaded 2026-08-05 and it is not "
            f"interchangeable with the deposited 3IKD at {DEPOSITED_3IKD}."
        )
    if verify:
        got = sha256(IAN_3IKD_SRC)
        if got != IAN_3IKD_SHA:
            raise ReceptorIdentityError(
                f"3IKD_ian has changed underneath us.\n"
                f"  path     {IAN_3IKD_SRC}\n"
                f"  expected {IAN_3IKD_SHA}\n"
                f"  found    {got}\n"
                f"Every 2.0.0 result was computed against the expected digest. "
                f"Either the file was re-uploaded (update IAN_3IKD_SHA and say "
                f"so in a decision record) or the wrong file is in place."
            )
    if not noligand:
        return IAN_3IKD_SRC
    if not IAN_3IKD_NOLIGAND.exists():
        raise ReceptorIdentityError(
            f"ligand-stripped 3IKD_ian is missing: {IAN_3IKD_NOLIGAND}. "
            f"Run scripts/prepare_3ikd_receptor.py."
        )
    return IAN_3IKD_NOLIGAND


def describe(path: Path) -> dict:
    """Identify which receptor a path is, for stamping onto a result row.

    Every number this project reports must carry the receptor that produced it
    (D0059). This returns something that can go straight into a CSV column.
    """
    p = Path(path).resolve()
    for name, ref in (("3IKD_ian", IAN_3IKD_SRC),
                      ("3IKD_ian_noligand", IAN_3IKD_NOLIGAND),
                      ("3IKD_deposited", DEPOSITED_3IKD),
                      ("6VAJ_superseded", SUPERSEDED_6VAJ)):
        if ref.exists() and p == ref.resolve():
            return {"receptor": name, "path": str(p)}
    # An unrecognised receptor is reported as unrecognised, never guessed at
    # from the filename -- "3IKD" in a path is exactly what is ambiguous here.
    return {"receptor": "UNRECOGNISED", "path": str(p)}
