"""
Purpose: #30 — does our pose set actually CONTAIN the crystal pose?
Author: Mike Hallett (with Claude Code)
Date: 2026-08-07
Input: the co-folding benchmark's 15 crystal complexes (ligand already in 3IKD frame)
Output: 00_outputs/blacksmith/pose_split/pose_split_validation_<N>.csv

@tt8804 in #30: *"we need to check if known crystal structures are always
contained within a set of split poses generated by our methodology."*

This is the acceptance test for pose splitting, and it is prior to it. Splitting
a pose set into modes can only surface a crystal pose that the set already holds.
If the 200-run set does not contain it, no clustering rule recovers it and the
whole 2.2.0 thesis needs restating -- so the containment question has to be
answered before the splitting rule is tuned.

THE PROTOCOL IS THE PRODUCTION ONE, NOT A CONVENIENT APPROXIMATION. Same
AutoDock-GPU reactive docking, same `--nrun 200`, same receptor, same flexible
Cys113 as `nac_screen_v2`. A validation run at lower effort would measure a
pipeline we do not run.

THREE DEPTHS ARE REPORTED AND THEY ANSWER DIFFERENT QUESTIONS.
  * all 200 poses  -- is the crystal pose reachable AT ALL by this search?
  * the kept 20    -- does it survive `KEEP_TOP` (the energy cut #23 indicted)?
  * the top 10     -- does it survive into the window the score actually reads?
The gap between the first and the last is the damage the energy ordering does,
measured rather than argued.

RMSD IS ELEMENT-AWARE AND SYMMETRY-CORRECTED, and the crystal ligand is the
ADDUCT -- it has lost its leaving group, so atom counts never match. This is the
same ruler used for the co-folding comparison, so the two are comparable.
"""

from __future__ import annotations

import argparse
import importlib.util
import logging
import sys
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "scripts"))

from shared import outputs as sout                  # noqa: E402

log = logging.getLogger("pose-split-val")
OUT = sout.Topic("blacksmith", "pose_split")
REFS = Path("/data/lab_vm/modifiable/inhibition/cofold/docking/refs")
SUCCESS_A = 2.0
KEEP_TOP = 20
TOPN = 10


def _load(name: str):
    spec = importlib.util.spec_from_file_location(
        name, REPO / "scripts" / f"{name}.py")
    m = importlib.util.module_from_spec(spec)
    # Registered BEFORE exec: @dataclass resolves its annotations through
    # sys.modules[cls.__module__], and a module loaded by spec alone is not
    # there yet, so nac_screen's frozen Candidate raises on import.
    sys.modules[name] = m
    spec.loader.exec_module(m)
    return m


def dlg_poses(dlg: Path) -> list[tuple[np.ndarray, np.ndarray]]:
    """Every docked ligand pose in the .dlg, as (coords, elements).

    Ligand records only: the flexible Cys sidechain is written into the same
    DOCKED block, and including it would drag every RMSD toward the receptor.
    """
    out, cur_x, cur_e = [], [], []
    for ln in dlg.read_text(errors="replace").splitlines():
        if ln.startswith("DOCKED: MODEL"):
            cur_x, cur_e = [], []
        elif ln.startswith("DOCKED: ENDMDL"):
            if cur_x:
                out.append((np.array(cur_x), np.array(cur_e)))
            cur_x, cur_e = [], []
        elif "DOCKED: ATOM" in ln or "DOCKED: HETATM" in ln:
            rec = ln.split("DOCKED: ", 1)[1]
            if rec[17:20].strip() in ("CYS", "HIS", "LYS", "ARG", "SER", "THR",
                                      "TYR", "ASP", "GLU", "ASN", "GLN", "MET"):
                continue                      # flexible receptor sidechain
            t = rec[77:79].strip().upper() if len(rec) > 78 else ""
            el = {"A": "C", "NA": "N", "OA": "O", "SA": "S", "HD": "H"}.get(
                t, (t or rec[12:16].strip()[:1]).upper())
            if el == "H":
                continue
            try:
                cur_x.append((float(rec[30:38]), float(rec[38:46]),
                              float(rec[46:54])))
                cur_e.append(el)
            except ValueError:
                pass
    if cur_x:
        out.append((np.array(cur_x), np.array(cur_e)))
    return out


def crystal(ident: str, cdc) -> tuple[np.ndarray, np.ndarray]:
    return cdc.elems_pdb(REFS / f"{ident}_ref.pdb")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ap.add_argument("--set", required=True)
    ap.add_argument("--gpu", default="3")
    ap.add_argument("--nrun", type=int, default=200)
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    ns = _load("nac_screen")
    cb = _load("cofold_bench")
    cdc = _load("cofold_docking_comparator")

    # THE CANDIDATES COME FROM THE SCREEN'S OWN BUILDER. All fifteen entries are
    # already in `covalent_links_3.csv`, so `crystal_positives` assigns each its
    # mechanism and reactive SMARTS by substructure match against
    # `warhead_classes_10.csv` -- the same assignment production uses. Labelling
    # them here by eye would be a second, divergent source of truth, and D0029
    # records that prose warhead labels already mislabelled the fumarate esters.
    wh = pd.read_csv(REPO / "data/reference/warhead_classes_10.csv")
    meta = {r.class_id: (r.mechanism, r.reactive_atom_smarts) for r in wh.itertuples()}
    by_pdb = {c.ident.split(":")[1]: c for c in ns.crystal_positives(meta, None)}

    rec_dir = ns.build_reactive_receptor(ns.RX_RECEPTOR)
    log.info("reactive receptor %s, nrun=%d, GPU %s", rec_dir, args.nrun, args.gpu)

    df = pd.read_csv(args.set)
    rows = []
    for r in df.itertuples():
        rec = {"ident": r.ident, "held_out": r.held_out, "comp_id": r.comp_id}
        try:
            cx, ce = crystal(r.ident, cdc)
            cand = by_pdb.get(r.ident)
            if cand is None:
                raise ValueError("no warhead class matched by SMARTS")
            rec["warhead_class"] = cand.warhead_class
            rec["mechanism"] = cand.mechanism
            work = Path(tempfile.mkdtemp(prefix="psval_"))
            ligs = ns.prepare_ligand(cand, work / "lig.pdbqt")
            best = None
            for j, lig in enumerate(ligs):
                dlg = ns.dock(lig, rec_dir, work / f"c{j}", args.nrun, args.gpu)
                poses = dlg_poses(dlg)
                en = ns.pose_energies(dlg)
                if not poses:
                    continue
                n = min(len(poses), len(en))
                rmsds = np.array([cb.sym_rmsd(px, pe, cx, ce)
                                  for px, pe in poses[:n]])
                if best is None or np.nanmin(rmsds) < np.nanmin(best[0]):
                    best = (rmsds, np.array(en[:n]))
            if best is None:
                raise ValueError("no poses")
            rmsds, en = best
            order = np.argsort(en)              # energy rank, as production does
            rec.update({
                "status": "ok", "n_poses": len(rmsds),
                "best_rmsd_all": float(np.nanmin(rmsds)),
                "best_rank_by_energy": int(np.where(
                    order == int(np.nanargmin(rmsds)))[0][0]) + 1,
                "hit_all_200": bool(np.nanmin(rmsds) <= SUCCESS_A),
                "hit_kept_20": bool(np.nanmin(rmsds[order[:KEEP_TOP]]) <= SUCCESS_A),
                "hit_top_10": bool(np.nanmin(rmsds[order[:TOPN]]) <= SUCCESS_A),
                "best_rmsd_kept_20": float(np.nanmin(rmsds[order[:KEEP_TOP]])),
                "best_rmsd_top_10": float(np.nanmin(rmsds[order[:TOPN]])),
            })
        except Exception as exc:                       # noqa: BLE001
            rec.update({"status": f"failed: {type(exc).__name__}: {exc}"[:160]})
        rows.append(rec)
        log.info("%s: %s", r.ident, rec.get("status") if rec["status"] != "ok"
                 else (f"best {rec['best_rmsd_all']:.2f} A at energy rank "
                       f"{rec['best_rank_by_energy']}/{rec['n_poses']}  "
                       f"200:{rec['hit_all_200']} 20:{rec['hit_kept_20']} "
                       f"10:{rec['hit_top_10']}"))
        # Checkpoint to a FIXED path. `OUT.write` mints a new numbered file on
        # every call, so checkpointing through it left 15 near-identical CSVs and
        # made "the result" ambiguous — the reader has to know that the highest
        # number is the only complete one. The versioned artefact is written once,
        # at the end.
        pd.DataFrame(rows).to_csv(OUT.dir / "_partial_pose_split_validation.csv",
                                  index=False)

    d = pd.DataFrame(rows)
    dest = OUT.write("pose_split_validation", ".csv")
    d.to_csv(dest, index=False)
    (OUT.dir / "_partial_pose_split_validation.csv").unlink(missing_ok=True)
    log.info("wrote %s", dest)
    ok = d[d.status == "ok"]
    if not len(ok):
        print("no successful cases"); return
    print(f"\n#30 — is the crystal pose CONTAINED in our pose set?  (n={len(ok)})\n")
    print(f"  within {SUCCESS_A} A anywhere in the {args.nrun} docked poses : "
          f"{ok.hit_all_200.mean()*100:5.1f}%")
    print(f"  ... surviving the KEEP_TOP {KEEP_TOP} energy cut             : "
          f"{ok.hit_kept_20.mean()*100:5.1f}%")
    print(f"  ... surviving into the top {TOPN} the score reads            : "
          f"{ok.hit_top_10.mean()*100:5.1f}%")
    print(f"\n  median best RMSD over all poses: {ok.best_rmsd_all.median():.2f} A")
    print("\n  The first number is what pose SPLITTING could ever recover.")
    print("  The drop to the third is what the energy ordering costs (#23).")


if __name__ == "__main__":
    main()
